### ISSUE TITLE
Wiki suggestions: LMS section

### ISSUE THREAD

**Issue by LolHacksRule** [Kinnay/Nintendo-File-Formats#1]
LMS stands for LibMS (LibMessageStudio), MSBT stands for **MeSsaGe STuDio BiNary Text** (**MsgStd** in the header stands for MeSsaGe STuDio, the internal tool translators use to make these files), MSBP stands for **MeSsaGe STuDio BiNary PRoJect**, the MSTXT files in it are related to the MSBT files in the software's filesystem, MSTXT files are uncompiled (XML) text, MSPROJ files are the exact same but for uncompiled projects.

**Comment by Kinnay** [comment]
Thanks. I've explained what mstxt files are in the msbp docs and the home page now mentions the full name of the LMS library.

In my opinion, explaining what the MSBT/MSBP/MsgStd abbreviations mean doesn't really add any useful information. I always try to be careful about the amount of details I add to the wiki pages to make sure that they don't become hard to read. The meaning of these abbreviations can be guessed fairly easily anyway.
