### ISSUE TITLE
Some improvements to PTCL. 

### ISSUE THREAD

**Issue by KillzXGaming** [kinnay/Nintendo-File-Formats#4]
For "Animation  Functions", type 0 is a single color/constant type.

Some adjustments to the emitter section.

| Offset | Size | Description |
| --- | --- | --- |
| 0x2CC | 4 | Offset into keyframe animation section |
| 0x2D0	| 4 | Size of keyframe animation section |
| 0x2D4 | 8 | Unknown |

Also a minor fix to some offsets/sizes.

| Offset | Size | Description |
| --- | --- | --- |
| 0x448 | 4 | Emission ratio randomness |
| 0x44C | 0x38 | Unknown |

Key Section
| Offset | Size | Description |
| --- | --- | --- |
| 0x00| 4 | Magic number (`KEYA`) |
| 0x4| 4 | Number of animation groups |
| 0x8 |   | Key Groups|

Key Group
| Offset | Size | Description |
| --- | --- | --- |
| 0x0| 4 | Number of keys. |
| 0x4| 4 | Unknown.|
| 0x8| 4 | Type |
| 0xC| 4 | Unknown |
| 0x10| 4 | Frame Count|
| 0x14| 4 | Unknown |
| 0x18| 4 | Section Size|
| 0x1C |   | Key Frames |

Key Frame
| Offset | Size | Description |
| --- | --- | --- |
| 0x0| 4 | Frame |
| 0x4| 4 | Value |

**Comment by kinnay** [comment]
Thank you! I updated the wiki page.

**Comment by KillzXGaming** [comment]
Also here are some types.

Color0/Color1 types uses the key table for 8 key types unlike Switch ptcl which is in the same emitter section with a time value.

Group Type
| Value | Description |
| ---  | --- |
| 5 | Rotation X |
| 6 | Rotation Y |
| 7 | Rotation Z |
| 17 |  Scale |
| 38 | Color 0 Red (8 Key) |
| 39 | 4 | Color 0 Green (8 Key) |
| 40 | 4 | Color 0 Blue (8 Key) |
| 41 | Color 1Red (8 Key) |
| 42 | 4 | Color 1 Green (8 Key) |
| 43 | 4 | Color 1 Blue (8 Key) |

**Comment by kinnay** [comment]
Thank you. This helped me figure out many more types too.

**Comment by KillzXGaming** [comment]
Here is the 4 key alpha animation section which can be confirmed by comparing some Switch ptcl alpha key values (which has direct value/times). The first key is always 0 and last is always 1 for the time values.

Key Frame
| Offset | Size | Description |
| --- | --- | --- |
| 0x0| 4 | First key value |
| 0x4| 4 | Value difference of first key value and second key value. |
| 0x8| 4 | Value difference of second key value and last key value. |
| 0xC| 4 | Time of second key value |
| 0x10| 4 | Time  of third key value. |

An example on getting the 4 keys and 3 values.

```
  float key1 = StartValue;
  float key2 = StartValue + StartDifference;
  float key4 = key3 + EndDifference;

  KeyFrame(0, key1)
  KeyFrame(Time2, key2)
  KeyFrame(Time3, key2 )
  KeyFrame(1, key4)
```

**Comment by kinnay** [comment]
Cool :+1:
